export enum ProductsTypeKeys {
    GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE',
    GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE',
    CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE',
}
